version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432" # Optional: if you need to connect to DB from host machine

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env # Load variables from the root .env file
      - ./backend/.env # Load backend-specific .env file (variables here override .env if names clash)
    environment:
      # Construct DATABASE_URL using variables from the root .env file
      # This will override DATABASE_URL if it's also set in ./backend/.env
      DATABASE_URL: postgresql://${PG_USER}:${PG_PASSWORD}@db:5432/${PG_DB}
    depends_on:
      - db
    # Optional: For development, you might want to mount your code
    # volumes:
    #   - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
